/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import java.awt.CardLayout;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JAGTAP
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    private Business business;
    private JPanel cardSequenceJPanel;
    public LoginPanel(Business business,JPanel cardSequenceJPanel) {
        initComponents();
        this.business=business;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reset();
    }
    public void reset()
    {
        userNameTextField.setText("");
        passwordField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setText("User Name");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameTextField)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton)
                            .addComponent(jLabel1))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(loginButton)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        byte temp=0;
        if(passwordField.getText().isEmpty() && userNameTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter User Name and password", "Error", 0);
        }
        else
        {
            int pass= passwordField.getText().hashCode();
            for(UserAccount ua : business.getUserDirectory().getListOfUserAccounts())
            {
                if((ua.getUserName()).matches(userNameTextField.getText()))
                {
                    if ((ua.getCount() > 2) || ua.getStatus()=='N')
                    {
                        temp=1;
                        JOptionPane.showMessageDialog(null, "The account is either locked or disabled, "
                            + "Please Contact Admin and reset user Account", TOOL_TIP_TEXT_KEY, HEIGHT);
                        break;
                    }
                    if (pass == ua.getPassword())
                    {
                        temp=1;
                        if (ua.getRole().matches("Admin"))
                        {
                            AdminWorkAreaPanel adminWorkAreaPanel = new AdminWorkAreaPanel(business,cardSequenceJPanel,ua);
                            cardSequenceJPanel.add("AdminWorkArea",adminWorkAreaPanel);
                            CardLayout cardLayout=(CardLayout) cardSequenceJPanel.getLayout();
                            cardLayout.next(cardSequenceJPanel);
                        }
                        else if (ua.getRole().matches("Supplier"))
                        {
                            SupplierWorkAreaPanel supplierWorkAreaPanel= new SupplierWorkAreaPanel(business,cardSequenceJPanel,ua);
                            cardSequenceJPanel.add("SupplierWorkArea",supplierWorkAreaPanel);
                            CardLayout cardLayout=(CardLayout)cardSequenceJPanel.getLayout();
                            cardLayout.next(cardSequenceJPanel);
                        }
                        else 
                        {
                            SalesPersonWorkAreaPanel salesPersonWorkAreaPanel = new SalesPersonWorkAreaPanel(business,cardSequenceJPanel,ua);
                            cardSequenceJPanel.add("SalesPersonWorkAreaPanel",salesPersonWorkAreaPanel);
                            CardLayout cardLayout=(CardLayout)cardSequenceJPanel.getLayout();
                            cardLayout.next(cardSequenceJPanel);
                        }
                    }
                    else
                    {
                        if(!ua.getRole().matches("Admin"))
                        {
                            ua.setCount((ua.getCount()+1));
                        }
                        if(ua.getCount() > 2)
                        {
                            temp=1;
                            JOptionPane.showMessageDialog(null, "Account Locked Please Contact Admin to reset your account", "Error", 0);
                        }
                        //else
                        //JOptionPane.showMessageDialog(null, "Invalid User Name and Password", "Error", 0);
                    }
                    break;
                }
            }
            if (temp ==0)
            {
                JOptionPane.showMessageDialog(null, "Invalid User Name and Password", "Error", 0);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
