/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JAGTAP
 */
public class ManageSupplierPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSupplierPanel
     */
    private Business business;
    private JPanel cardSequenceJPanel;
    private int temp=0;
    public ManageSupplierPanel(Business business,JPanel cardSequenceJPanel) {
        initComponents();
        this.business=business;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reload();
    }
    
    private void reload()
    {
        temp=0;
        supplierComboBox.removeAllItems();
        for(Supplier s:business.getSupplierDirectory().getListOfSuppliers())
        {
            supplierComboBox.addItem(s);
        }
        saveButton.setEnabled(false);
        suppNameTextField.setEnabled(false);
        nameTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        addressTextField.setEnabled(false);
        userNameTextField.setEnabled(false);
        activeRadioButton.setEnabled(false);
        disabledsRadioButton.setEnabled(false);
        //populateSupplier();
    }
    private void populateSupplier()
    {
        Supplier s = (Supplier)supplierComboBox.getSelectedItem();
        suppNameTextField.setText(s.getName());
        UserAccount ua = s.getUserAccount();
        Person p = ua.getPerson();
        nameTextField.setText(p.getName());
        addressTextField.setText(p.getAddress());
        emailTextField.setText(p.getEmail());
        userNameTextField.setText(ua.getUserName());
        roleTextField.setText(ua.getRole());
        if(ua.getStatus()=='Y')
            activeRadioButton.setSelected(true);
        else
            disabledsRadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        supplierComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        activeRadioButton = new javax.swing.JRadioButton();
        disabledsRadioButton = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JButton();
        roleTextField = new javax.swing.JTextField();
        rstPwdButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        suppNameTextField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Manage Supplier");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        supplierComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supplierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        nameTextField.setEnabled(false);

        jLabel3.setText("Address");

        jLabel4.setText("Email");

        addressTextField.setEnabled(false);

        emailTextField.setEnabled(false);

        activeRadioButton.setText("Active");
        activeRadioButton.setEnabled(false);
        activeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeRadioButtonActionPerformed(evt);
            }
        });

        disabledsRadioButton.setText("Disabled");
        disabledsRadioButton.setEnabled(false);

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        roleTextField.setEnabled(false);
        roleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleTextFieldActionPerformed(evt);
            }
        });

        rstPwdButton.setText("Reset Password");
        rstPwdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstPwdButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("User Name");

        userNameTextField.setEnabled(false);

        jLabel6.setText("Role");

        jLabel7.setText("Status");

        addButton.setText("Add ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Supplier Name");

        suppNameTextField.setEnabled(false);

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton)
                            .addComponent(viewButton))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(activeRadioButton)
                                            .addComponent(disabledsRadioButton)))
                                    .addComponent(roleTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rstPwdButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(addButton)))
                                .addGap(18, 18, 18)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(63, 63, 63)
                                .addComponent(suppNameTextField)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(suppNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(activeRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(disabledsRadioButton)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rstPwdButton)
                    .addComponent(addButton)
                    .addComponent(updateButton))
                .addGap(30, 30, 30)
                .addComponent(saveButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void activeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeRadioButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if((userNameTextField.getText().isEmpty()) || (nameTextField.getText().isEmpty()) || 
           (addressTextField.getText().isEmpty())  || (emailTextField.getText().isEmpty()) || (suppNameTextField.getText().isEmpty()))
            JOptionPane.showMessageDialog(null, "Please Enter the required details", "Error", 0);
        else
        {
            if(temp==1)
            {
                Supplier s = (Supplier)supplierComboBox.getSelectedItem();
                s.setName(suppNameTextField.getText());
                 UserAccount userAccount = s.getUserAccount();
                userAccount.setUserName(userNameTextField.getText());
                userAccount.setRole("Supplier");
                Person p = userAccount.getPerson();
                p.setName(nameTextField.getText());
                p.setAddress(addressTextField.getText());
                p.setEmail(emailTextField.getText());
                if(activeRadioButton.isSelected())
                    userAccount.setStatus('Y');
                else
                    userAccount.setStatus('N');
                JOptionPane.showMessageDialog(null, "Supplier Updated successfully");
                updateButton.setEnabled(true);
            }
            else
            {
                Supplier s=business.getSupplierDirectory().addSupplier();
                s.getProductCatlog().setSupplier(s);
                UserAccount ua = business.getUserDirectory().addUser();
                Person p = ua.getPerson();
                p.setName(nameTextField.getText());
                p.setAddress(addressTextField.getText());
                p.setEmail(emailTextField.getText());
                ua.setUserName(userNameTextField.getText());
                ua.setRole("Supplier");
                ua.setPassword("pass".hashCode());
                s.setName(suppNameTextField.getText());
                s.setUserAccount(ua);
                business.getMasterProductCatlog().addProductCatlog(s.getProductCatlog());
                JOptionPane.showMessageDialog(null, "Supplier Added successfully");
                addButton.setEnabled(true);
            }
            reload();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void roleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleTextFieldActionPerformed

    private void rstPwdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstPwdButtonActionPerformed
        // TODO add your handling code here:
        Supplier s = (Supplier)supplierComboBox.getSelectedItem();
        UserAccount userAccount = s.getUserAccount();
        userAccount.setPassword("pass".hashCode());
        userAccount.setCount(0);
        JOptionPane.showMessageDialog(null, "Password reset successfully");
    }//GEN-LAST:event_rstPwdButtonActionPerformed

    private void supplierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierComboBoxActionPerformed
        // TODO add your handling code here:
        //populateSupplier();
        suppNameTextField.setText("");
        nameTextField.setText("");
        emailTextField.setText("");
        addressTextField.setText("");
        userNameTextField.setText("");
        roleTextField.setText("");
        activeRadioButton.setSelected(false);
        disabledsRadioButton.setSelected(false);
    }//GEN-LAST:event_supplierComboBoxActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(true);
        suppNameTextField.setEnabled(true);
        nameTextField.setEnabled(true);
        emailTextField.setEnabled(true);
        addressTextField.setEnabled(true);
        userNameTextField.setEnabled(true);
        activeRadioButton.setEnabled(true);
        disabledsRadioButton.setEnabled(true);
        temp=1;
        updateButton.setEnabled(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(true);
        suppNameTextField.setEnabled(true);
        nameTextField.setEnabled(true);
        emailTextField.setEnabled(true);
        addressTextField.setEnabled(true);
        userNameTextField.setEnabled(true);
        activeRadioButton.setEnabled(true);
        disabledsRadioButton.setEnabled(true);
        addButton.setEnabled(false);
        suppNameTextField.setText("");
        nameTextField.setText("");
        emailTextField.setText("");
        addressTextField.setText("");
        userNameTextField.setText("");
        roleTextField.setText("Supplier");
        activeRadioButton.setSelected(true);
        disabledsRadioButton.setSelected(false);    
    }//GEN-LAST:event_addButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        populateSupplier();
    }//GEN-LAST:event_viewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadioButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton disabledsRadioButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField roleTextField;
    private javax.swing.JButton rstPwdButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField suppNameTextField;
    private javax.swing.JComboBox supplierComboBox;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
