/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author JAGTAP
 */
public class MonitorSalesPerformancePanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitorSalesPerformancePanel
     */
    private Business business;
    private JPanel cardSequenceJPanel;
    private ArrayList<MonitorSales> listOfMonitorSales;
    public MonitorSalesPerformancePanel(Business business,JPanel cardSequenceJPanel) {
        initComponents();
        this.business=business;
        this.cardSequenceJPanel=cardSequenceJPanel;
        listOfMonitorSales=business.getListOfMonitorSales();
        loadDataToMonitorSales();
    }
    
    private void loadDataToMonitorSales()
    {
        for(Order o : business.getOrdersDirectory().getListOfOrders())
        {
            if (o.getStatus()=='Y')
            {
                for(OrderItems oi : o.getListOfOrderItems())
                {
                    if(oi.isStatus())
                    {
                        MonitorSales ms = business.addMonitorSales();
                        //monitorSales.
                        ms.setOrderid(o.getId());
                        ms.setMarketType(o.getMarketOffer().getMarket().getType());
                        ms.setSalesUserName(o.getSalesPerson().getUserAccount().getUserName());
                        ms.setSalesPersonsName(o.getSalesPerson().getUserAccount().getPerson().getName());
                        ms.setOrganizationName(o.getCustomer().getOrganization());
                        ms.setTotalActualOrderPrice(o.totalActualOrderPrice());
                        ms.setTotalTargetOrderPrice(o.totalTargetOrderPrice());
                        if(ms.getTotalActualOrderPrice() > ms.getTotalTargetOrderPrice())
                            ms.setOrderDealFlag('A');
                        else if(ms.getTotalActualOrderPrice() < ms.getTotalTargetOrderPrice())
                            ms.setOrderDealFlag('B');
                        else
                            ms.setOrderDealFlag('E');
                        ms.setProductId(oi.getProduct().getProductId());
                        ms.setProductName(oi.getProduct().getName());
                        ms.setSupplierName(oi.getProduct().getProductCatlog().getSupplier().getName());
                        ms.setTotOrderItemActualPrice(oi.getTotalAuctualPrice());
                        ms.setTotOrderItemTargetPrice(oi.getTotalTargetPrice());
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        totRevenueButton = new javax.swing.JButton();
        prodSalesRevenueBymarketButton = new javax.swing.JButton();
        top10SalesPersonButton = new javax.swing.JButton();
        salesPersonAbvTargetSalesButton = new javax.swing.JButton();
        SalesPersonBelowTargetSalesButton = new javax.swing.JButton();
        top3ProductsButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Monitor Sales Performance");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        totRevenueButton.setText("Total Revenue");
        totRevenueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totRevenueButtonActionPerformed(evt);
            }
        });

        prodSalesRevenueBymarketButton.setText("Product Sales Revenues by market");
        prodSalesRevenueBymarketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSalesRevenueBymarketButtonActionPerformed(evt);
            }
        });

        top10SalesPersonButton.setText("Top 10 Sales Person");
        top10SalesPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top10SalesPersonButtonActionPerformed(evt);
            }
        });

        salesPersonAbvTargetSalesButton.setText("Sales Person with above Target sales");
        salesPersonAbvTargetSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesPersonAbvTargetSalesButtonActionPerformed(evt);
            }
        });

        SalesPersonBelowTargetSalesButton.setText("Sales Person with below Target Sales");
        SalesPersonBelowTargetSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesPersonBelowTargetSalesButtonActionPerformed(evt);
            }
        });

        top3ProductsButton.setText("Top 3 products consistently sold above target Price");
        top3ProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top3ProductsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(top3ProductsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SalesPersonBelowTargetSalesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salesPersonAbvTargetSalesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(top10SalesPersonButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totRevenueButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prodSalesRevenueBymarketButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addComponent(totRevenueButton)
                .addGap(18, 18, 18)
                .addComponent(prodSalesRevenueBymarketButton)
                .addGap(18, 18, 18)
                .addComponent(top10SalesPersonButton)
                .addGap(18, 18, 18)
                .addComponent(salesPersonAbvTargetSalesButton)
                .addGap(18, 18, 18)
                .addComponent(SalesPersonBelowTargetSalesButton)
                .addGap(18, 18, 18)
                .addComponent(top3ProductsButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totRevenueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totRevenueButtonActionPerformed
        // TODO add your handling code here:
        TotalRevenuePanel totalRevenuePanel = new TotalRevenuePanel(business,cardSequenceJPanel);
        cardSequenceJPanel.add("TotalRevenue",totalRevenuePanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_totRevenueButtonActionPerformed

    private void prodSalesRevenueBymarketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSalesRevenueBymarketButtonActionPerformed
        // TODO add your handling code here:
        ProductSalesRevenuePanel productSalesRevenuePanel = new ProductSalesRevenuePanel(business,cardSequenceJPanel,listOfMonitorSales);
        cardSequenceJPanel.add("ProductSalesRevenue",productSalesRevenuePanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_prodSalesRevenueBymarketButtonActionPerformed

    private void top10SalesPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top10SalesPersonButtonActionPerformed
        // TODO add your handling code here:
        Top10SalesPersonPanel top10SalesPersonPanel= new Top10SalesPersonPanel(business,cardSequenceJPanel,listOfMonitorSales);
        cardSequenceJPanel.add("Top10SalesPerson",top10SalesPersonPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_top10SalesPersonButtonActionPerformed

    private void salesPersonAbvTargetSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesPersonAbvTargetSalesButtonActionPerformed
        // TODO add your handling code here:
        SalesPersonAbvTargetSalesPanel salesPersonAbvTargetSalesPanel= new SalesPersonAbvTargetSalesPanel(business,cardSequenceJPanel,listOfMonitorSales);
        cardSequenceJPanel.add("SalesPersonAbove",salesPersonAbvTargetSalesPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_salesPersonAbvTargetSalesButtonActionPerformed

    private void SalesPersonBelowTargetSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesPersonBelowTargetSalesButtonActionPerformed
        // TODO add your handling code here:
        SalesPersonBelowTargetPanel salesPersonBelowTargetPanel= new SalesPersonBelowTargetPanel(business,cardSequenceJPanel,listOfMonitorSales);
        cardSequenceJPanel.add("SalesPersonBelow",salesPersonBelowTargetPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_SalesPersonBelowTargetSalesButtonActionPerformed

    private void top3ProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top3ProductsButtonActionPerformed
        // TODO add your handling code here:
        Top3ProductPanel top3ProductPanel= new Top3ProductPanel(business,cardSequenceJPanel,listOfMonitorSales);
        cardSequenceJPanel.add("Top3Product",top3ProductPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_top3ProductsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalesPersonBelowTargetSalesButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton prodSalesRevenueBymarketButton;
    private javax.swing.JButton salesPersonAbvTargetSalesButton;
    private javax.swing.JButton top10SalesPersonButton;
    private javax.swing.JButton top3ProductsButton;
    private javax.swing.JButton totRevenueButton;
    // End of variables declaration//GEN-END:variables
}
