/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JAGTAP
 */
public class SalesPersonWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPersonWorkAreaPanel
     */
    private Business business;
    private UserAccount userAccount;
    private JPanel cardSequenceJPanel;
    private SalesPerson salesPerson;
    public SalesPersonWorkAreaPanel(Business business,JPanel cardSequenceJPanel, UserAccount userAccount) {
        initComponents();
        this.business=business;
        this.cardSequenceJPanel=cardSequenceJPanel;
        this.userAccount=userAccount;
        this.userAccount.setCount(0);
        reload();
        salesPerson=IdentifySalesPerson();
    }
     public void reload()
    {
        userNameTextField.setText(userAccount.getUserName());
        nameTextField.setText(userAccount.getPerson().getName());
        roleTextField.setText(userAccount.getRole());
        if(userAccount.getPassword()=="pass".hashCode())
        {
            JOptionPane.showMessageDialog(null, "Please change your default password");
        }
    }
    private SalesPerson IdentifySalesPerson()
    {
        for(SalesPerson sp:business.getSalesPersonsDirectory().getListOfSalesPersons())
        {
            if((sp.getUserAccount().getUserName().equals(userAccount.getUserName())) &&
                (sp.getUserAccount().getPassword()==userAccount.getPassword()))
            {
                return sp;
            }
        }        
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        roleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        changePwdButton2 = new javax.swing.JButton();
        regCustButton = new javax.swing.JButton();

        jLabel1.setText("username");

        jLabel2.setText("Name ");

        jLabel3.setText("Role");

        userNameTextField.setEnabled(false);

        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        roleTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Sales Person Work Area");

        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        changePwdButton2.setText("Change Password");
        changePwdButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdButton2ActionPerformed(evt);
            }
        });

        regCustButton.setText("Register Customer");
        regCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCustButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regCustButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTextField)
                            .addComponent(userNameTextField)
                            .addComponent(roleTextField)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(placeOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changePwdButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(placeOrderButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(18, 18, 18)
                .addComponent(changePwdButton2)
                .addGap(18, 18, 18)
                .addComponent(regCustButton)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
        PlaceOrderPanel placeOrderPanel = new PlaceOrderPanel(business,cardSequenceJPanel,salesPerson);
        cardSequenceJPanel.add("PlaceOrderPanel",placeOrderPanel);
        CardLayout cardLayout=(CardLayout)cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Component component = cardSequenceJPanel.getComponent((cardSequenceJPanel.getComponentCount()-2));
        LoginPanel loginPanel = (LoginPanel) component;
        loginPanel.reset();
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void changePwdButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdButton2ActionPerformed
        // TODO add your handling code here:
        ChangePasswordPanel changePasswordPanel=new ChangePasswordPanel(userAccount,cardSequenceJPanel);
        cardSequenceJPanel.add("ChangePassword",changePasswordPanel);
        CardLayout cardLayout=(CardLayout)cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_changePwdButton2ActionPerformed

    private void regCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCustButtonActionPerformed
        // TODO add your handling code here:
        CustomerRegistrationPanel crp=new CustomerRegistrationPanel(business, cardSequenceJPanel, salesPerson);
        cardSequenceJPanel.add("CustomerRegistration",crp);
        CardLayout cardLayout=(CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_regCustButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePwdButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JButton regCustButton;
    private javax.swing.JTextField roleTextField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
