/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAGTAP
 */
public class Top10SalesPersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form Top10SalesPersonPanel
     */
    private Business business;
    private JPanel cardSequenceJPanel;
    private ArrayList<MonitorSales> listOfMonitorSales;
    private ArrayList<TopSalesPersonClass> listOfTopSalesPerson;
    public Top10SalesPersonPanel(Business business,JPanel cardSequenceJPanel,ArrayList<MonitorSales> listOfMonitorSales) {
        initComponents();
        this.business=business;
        this.cardSequenceJPanel=cardSequenceJPanel;
        this.listOfMonitorSales=listOfMonitorSales;
        listOfTopSalesPerson=new ArrayList<TopSalesPersonClass>();
        loadTopSales();
    }
    
    private void loadTopSales()
    {
        for(SalesPerson s : business.getSalesPersonsDirectory().getListOfSalesPersons())
        {
            for(Market m: business.getMarketList().getListOfMarkets())
            {
                TopSalesPersonClass t = new TopSalesPersonClass();
                t.setUserid(s.getUserAccount().getUserName());
                t.setName(s.getUserAccount().getPerson().getName());
                t.setTotalRevenue(s.getTotalRevenue());
                t.setTotalTargetRevenue(s.getTotalTargetRevenue());
                t.setMarketType(m.getType());
                t.setTotalMarketRevenue(s.getTotalRevenueByMarket(m.getType()));
                t.setTotalTargetMarketRevenue(s.getTotalTagetRevenueByMarket(m.getType()));
                listOfTopSalesPerson.add(t);
            }
        }
        Collections.sort(listOfTopSalesPerson, new TopSalesPersonComparator());
        DefaultTableModel dtm =(DefaultTableModel) salesPersonTable.getModel();
        dtm.setRowCount(0);
        int count = 0;
        for(TopSalesPersonClass t : listOfTopSalesPerson)
        {
            Object row[]=new Object[5];
            row[0]=t.getUserid();
            row[1]=t.getName();
            row[2]=t.getMarketType();
            row[3]=t.getTotalMarketRevenue();
            row[4]=t.getTotalMarketRevenue()-t.getTotalTargetMarketRevenue();
            dtm.addRow(row);
            count++;
            if(count==business.getMarketList().getListOfMarkets().size()*10)
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesPersonTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Top 10 Sales Person");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        salesPersonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "Name", "Market type", "Revenue", "Gap"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salesPersonTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesPersonTable;
    // End of variables declaration//GEN-END:variables
}
