/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author JAGTAP
 */
public class CreateAirlinerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlinerPanel
     */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public CreateAirlinerPanel(TravelAgency travelAgency, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
    }
    public void disableFields()
    {
        nameTextField.setEnabled(false);
        iATATextField.setEnabled(false);
        iCAOTextField.setEnabled(false);
        countryTextField.setEnabled(false);
        mainHubTextField.setEnabled(false);
        addAirplanesButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iATATextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iCAOTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mainHubTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addAirplanesButton = new javax.swing.JButton();

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Airliner");

        jLabel2.setText("Name");

        jLabel3.setText("IATA");

        jLabel4.setText("ICAO");

        jLabel5.setText("Main Hub");

        jLabel6.setText("Country");

        addAirplanesButton.setText("Add Airplanes");
        addAirplanesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirplanesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAirplanesButton)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField)
                            .addComponent(iATATextField)
                            .addComponent(iCAOTextField)
                            .addComponent(mainHubTextField)
                            .addComponent(countryTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAirplanesButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(iATATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(iCAOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mainHubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAirplanesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirplanesButtonActionPerformed
        // TODO add your handling code here:
        if ((nameTextField.getText().isEmpty()) || (iATATextField.getText().isEmpty()) || 
            (iCAOTextField.getText().isEmpty()) || (countryTextField.getText().isEmpty()) ||
            (mainHubTextField.getText().isEmpty()))
            JOptionPane.showMessageDialog(null, "Please enter the airliner details before adding airplane", "Error", 0);
        else
        {
            try
            {
                Airliners airliners=travelAgency.addAirliners(nameTextField.getText());
                airliners.setAirlines(nameTextField.getText());
                airliners.setCountry(countryTextField.getText());
                airliners.setMainHub(mainHubTextField.getText());
                airliners.setiATA(iATATextField.getText());
                airliners.setiCAO(iCAOTextField.getText());
                Fleet fleet=new Fleet();
                fleet.setAirliners(airliners);
                airliners.setFleet(fleet);
                FlightSchedule flightSchedule = travelAgency.getMasterSchedule().addFlightSchedule(airliners);
                airliners.setFlightSchedule(flightSchedule);
                //flightSchedule.setAirliners(airliners);
                AddingAirplanePanel addingAirplanePanel = new AddingAirplanePanel(fleet,cardSequenceJPanel);
                cardSequenceJPanel.add("AddingAirplane",addingAirplanePanel);
                CardLayout cardLayout= (CardLayout) cardSequenceJPanel.getLayout();
                cardLayout.next(cardSequenceJPanel);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Existing Airliner", "Error", 0);
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_addAirplanesButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirplanesButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField iATATextField;
    private javax.swing.JTextField iCAOTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mainHubTextField;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
