/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import com.sun.imageio.plugins.jpeg.JPEG;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JAGTAP
 */
public class FlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightPanel
     */
    private TravelAgency travelAgency;
    private Airliners airliners;
    private Airplane airplane;
    private JPanel cardSequenceJPanel;
    public FlightPanel(TravelAgency travelAgency,Airplane airplane, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.airliners=airplane.getFleet().getAirliners();
        this.airplane=airplane;
        this.cardSequenceJPanel=cardSequenceJPanel;
        loadAirplaneData();
    }
    
    private void loadAirplaneData()
    {
        airlinerTextField.setText(airliners.getAirlines());
        airplaneIdTextField.setText(String.valueOf(airplane.getAirplaneId()));
        manufacturingYearTextField.setText(String.valueOf(airplane.getManufacturingYear()));
        modelNumTextField.setText(airplane.getModelNumber());
        companyTextField.setText(airplane.getManufacturingCompany());
        totalSeatsTextField.setText(String.valueOf(airplane.getTotalSeats()));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        depaturePortTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destinationPortTextField = new javax.swing.JTextField();
        scheduleButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pricePerSeatTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        airplaneIdTextField = new javax.swing.JTextField();
        modelNumTextField = new javax.swing.JTextField();
        companyTextField = new javax.swing.JTextField();
        manufacturingYearTextField = new javax.swing.JTextField();
        totalSeatsTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("        Schedule Flight ");

        jLabel2.setText("Flight Id");

        jLabel3.setText("Date (mm-dd-yyyy)");

        jLabel4.setText("Time 24hrs (mm:ss)");

        jLabel5.setText("Depature Port");

        jLabel6.setText("Destination Port");

        scheduleButton.setText("Schedule");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Price per Seat");

        pricePerSeatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerSeatTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Airliner");

        airlinerTextField.setEnabled(false);

        jLabel11.setText("Airplane Id");

        airplaneIdTextField.setEnabled(false);

        modelNumTextField.setEnabled(false);

        companyTextField.setEnabled(false);

        manufacturingYearTextField.setEnabled(false);
        manufacturingYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturingYearTextFieldActionPerformed(evt);
            }
        });

        totalSeatsTextField.setEnabled(false);
        totalSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSeatsTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Seats");

        jLabel8.setText("Manufacturing Year");

        jLabel12.setText("Company");

        jLabel13.setText("Model Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scheduleButton)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(depaturePortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(flightIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(destinationPortTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(pricePerSeatTextField))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(91, 91, 91)
                                .addComponent(airlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(manufacturingYearTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(companyTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelNumTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airplaneIdTextField)
                                    .addComponent(totalSeatsTextField))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(flightIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scheduleButton)
                        .addComponent(jLabel10))
                    .addComponent(airlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(depaturePortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(destinationPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pricePerSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(airplaneIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(manufacturingYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pricePerSeatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerSeatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerSeatTextFieldActionPerformed

    private void manufacturingYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturingYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturingYearTextFieldActionPerformed

    private void totalSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSeatsTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        // TODO add your handling code here:
        if((flightIdTextField.getText().isEmpty()) || (depaturePortTextField.getText().isEmpty()) ||
           (destinationPortTextField.getText().isEmpty()) || (dateTextField.getText().isEmpty()) ||
           (timeTextField.getText().isEmpty()) || (pricePerSeatTextField.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Please enter all the flight details", "Error", 0);
        }
        else
        {
            try
            {
                int id = Integer.parseInt(flightIdTextField.getText());
                double price = Double.parseDouble(pricePerSeatTextField.getText());
                if((id >=0) && (price >=0))
                {
                    try
                    {
                        byte flag = dateValidation(dateTextField.getText());
                        if(flag == 0)
                        {
                            SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy"); 
                            Date date = (Date)dateFormat.parse(dateTextField.getText());
                            Date currdate = (Date)dateFormat.parse(dateFormat.format(new Date()));
                            flag = timeValidation(timeTextField.getText());
                            if (flag == 0)
                            {
                                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
                                Date time = (Date)timeFormat.parse(timeTextField.getText());
                                Date currtime = (Date)timeFormat.parse(timeFormat.format(new Date()));
                                if (((date.equals(currdate)) && (time.after(currtime))) || (date.after(currdate)))
                                {
                                    Flight flight = airliners.getFlightSchedule().addFlight();
                                    flight.setAirplane(airplane);
                                    airplane.getAirplaneListOfFlight().add(flight);
                                    flight.setDepatureDate(dateTextField.getText());
                                    flight.setDepaturePort(depaturePortTextField.getText());
                                    flight.setDepatureTime(timeTextField.getText());
                                    flight.setDestinationPort(destinationPortTextField.getText());
                                    flight.setFlightId(id);
                                    flight.setPriceOfSeat(price);
                                    JOptionPane.showMessageDialog(null, "Filght Scheduled Successfully");
                                }
                                else 
                                    JOptionPane.showMessageDialog(null, "Please Enter Todays or future depature Date and time", "Error", 0);
                            }
                            else
                                JOptionPane.showMessageDialog(null, "Improper time format please enter time in HH:mm(24 hrs) format ", "Error", 0);
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Improper date format please enter date in MM-dd-yyyy format ", "Error", 0);
                    }
                    catch(Exception e)
                    {
                            JOptionPane.showMessageDialog(null, "Please enter date in MM-dd-yyyy & Time in HH:mm(24 hrs) format ", "Error", 0);
                            e.printStackTrace();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Flight Id and Price / Seat can't be negative", "Error", 0);
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Flight Id and Price per seat are numeric fields", "Error", 0);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_scheduleButtonActionPerformed

    private byte dateValidation(String depatDateTextField)
    {
        if (depatDateTextField.matches("^[0-1][0-9][-][0-3][0-9][-][0-9][0-9][0-9][0-9]"))
        {
               if (((depatDateTextField.charAt(0)=='1') && (depatDateTextField.charAt(1)<'3')) ||
                   ((depatDateTextField.charAt(0)=='0') && (depatDateTextField.charAt(1)<='9')))
               {
                    if (((depatDateTextField.charAt(3)=='0') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='1') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='2') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='3') && (depatDateTextField.charAt(4)<'2')))
                    {
                         if(((depatDateTextField.charAt(0)=='0') && (depatDateTextField.charAt(1)=='2') &&
                             (depatDateTextField.charAt(3)=='3')) || 
                            ((depatDateTextField.charAt(0)=='0') && ((depatDateTextField.charAt(1)=='4') || (depatDateTextField.charAt(1)=='6') ||
                                                                              (depatDateTextField.charAt(1)=='9')) &&
                                                                             (depatDateTextField.charAt(3)=='3') && (depatDateTextField.charAt(4)=='1') ) ||
                            ((depatDateTextField.charAt(0)=='1') && (depatDateTextField.charAt(1)=='1') && (depatDateTextField.charAt(3)=='3') && 
                                 (depatDateTextField.charAt(4)=='1') ))
                         {
                               return 1;
                         }
                         else
                         {
                               return 0;
                         }
                    }
                     
                }
                            
        }
        return 1;                      
    }
    
    private byte timeValidation(String depatTimeTextField)
    {
        if (depatTimeTextField.matches("^[0-2][0-9][:][0-5][0-9]"))
        {
            if (((depatTimeTextField.charAt(0)=='2') && (depatTimeTextField.charAt(1) < '4')) ||
                 ((depatTimeTextField.charAt(0)=='1') && (depatTimeTextField.charAt(1) <='9'))||
                 ((depatTimeTextField.charAt(0)=='0') && (depatTimeTextField.charAt(1) <='9')))
            {
                return 0;
            }
        }
        return 1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JTextField airplaneIdTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField depaturePortTextField;
    private javax.swing.JTextField destinationPortTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField manufacturingYearTextField;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField pricePerSeatTextField;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField totalSeatsTextField;
    // End of variables declaration//GEN-END:variables
}
