/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author JAGTAP
 */
public class ManageAirliners extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliners
     */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public ManageAirliners(TravelAgency travelAgency,JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createtAirlinerButton = new javax.swing.JButton();
        listOfAirlinersButton = new javax.swing.JButton();
        createFlightButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("         Manage Airliners");

        createtAirlinerButton.setText("Create Airliner");
        createtAirlinerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createtAirlinerButtonActionPerformed(evt);
            }
        });

        listOfAirlinersButton.setText("List Of Airliners");
        listOfAirlinersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfAirlinersButtonActionPerformed(evt);
            }
        });

        createFlightButton.setText("Create Flight");
        createFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listOfAirlinersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createtAirlinerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(createtAirlinerButton)
                .addGap(29, 29, 29)
                .addComponent(listOfAirlinersButton)
                .addGap(34, 34, 34)
                .addComponent(createFlightButton)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listOfAirlinersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfAirlinersButtonActionPerformed
        // TODO add your handling code here:
        ListOfAirlinersPanel listOfAirlinersPanel = new ListOfAirlinersPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("ListOfAirliners",listOfAirlinersPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_listOfAirlinersButtonActionPerformed

    private void createtAirlinerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createtAirlinerButtonActionPerformed
        // TODO add your handling code here:
        CreateAirlinerPanel createAirlinerPanel = new CreateAirlinerPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("CreateAirliner",createAirlinerPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_createtAirlinerButtonActionPerformed

    private void createFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightButtonActionPerformed
        // TODO add your handling code here:
        AirlinerForFlightPanel airlinerForFlightPanel = new AirlinerForFlightPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("AirlerForFlight",airlinerForFlightPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_createFlightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createFlightButton;
    private javax.swing.JButton createtAirlinerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listOfAirlinersButton;
    // End of variables declaration//GEN-END:variables
}
